server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      access-token-expiration: 900000
      refresh-token-expiration: 604800000

logging:
  level:
    com.taskmanager: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG